In [62]:
import json
import pandas as pd

##  1).RESULTS

In [63]:
with open('t20_wc_match_results.json') as f:
    data=json.load(f)
    
print(len(data))

x=data[0]['matchSummary']
df=pd.DataFrame(x)
df.head()

1

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [64]:
df.shape

(45, 7)

In [65]:
df.rename({'scorecard':'match_id'}, axis=1,inplace=True)
df.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [66]:
df.to_csv('match_results.csv', index=False)

## 2). BATTING SUMMARY

In [67]:
with open('t20_wc_batting_summary.json') as d:
    data1=json.load(d)
    all_records=[]
    for rec in data1:
        all_records.extend(rec['battingSummary'])
result=pd.DataFrame(all_records)
result.head(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/†Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c †Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis†,c †Green b Wiese,6,6,0,0,100.00

In [68]:
result.head(5)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33

In [69]:
result.shape

(699, 10)

In [70]:
result['Out/Not_Out']=result['dismissal'].apply(lambda x: 'Out' if len(x)>0 else 'Not_Out')

result.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,Out/Not_Out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,Out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,Out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,1,2,166.66,Out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,Out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,Out

In [71]:
result.drop(columns=['dismissal'], inplace=True)

In [72]:
result.head()

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,Out/Not_Out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,Out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,Out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,Out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,Out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,Out

In [73]:
print(result['batsmanName'])

0          Michael van Lingen
1               Divan la Cock
2      Jan Nicol Loftie-Eaton
3               Stephan Baard
4          Gerhard Erasmus(c)
                ...
694                 Phil Salt
695                Ben Stokes
696               Harry Brook
697                 Moeen Ali
698          Liam Livingstone
Name: batsmanName, Length: 699, dtype: object

In [74]:
result['batsmanName'] = result['batsmanName'].apply(lambda x: x.replace('(c)†',''))
result['batsmanName'] = result['batsmanName'].apply(lambda x: x.replace('†',''))
result['batsmanName'] = result['batsmanName'].apply(lambda x: x.replace('(c)',''))

In [75]:
result.tail(20)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,Out/Not_Out
679,India Vs England,India,7,Ravichandran Ashwin,0,0,0,0,-,Not_Out
680,India Vs England,England,1,Jos Buttler,80,49,9,3,163.26,Not_Out
681,India Vs England,England,2,Alex Hales,86,47,4,7,182.97,Not_Out
682,Pakistan Vs England,Pakistan,1,Mohammad Rizwan,15,14,0,1,107.14,Out
683,Pakistan Vs England,Pakistan,2,Babar Azam,32,28,2,0,114.28,Out
684,Pakistan Vs England,Pakistan,3,Mohammad Haris,8,12,1,0,66.66,Out
685,Pakistan Vs England,Pakistan,4,Shan Masood,38,28,2,1,135.71,Out
686,Pakistan Vs England,Pakistan,5,Iftikhar Ahmed,0,6,0,0,0.00,Out
687,Pakistan Vs England,Pakistan,6,Shadab Khan,20,14,2,0,142.85,Out
688,Pakistan Vs England,Pakistan,7,Mohammad Nawaz,5,7,0,0,71.42,Out
689,Pakistan Vs England,Pakistan,8,Mohammad Wasim,4,8,0,0,50.00,Out
690,Pakistan Vs England,Pakistan,9,Shaheen Shah Afridi,5,3,1,0,166.66,Not_Out
691,Pakistan Vs England,Pakistan,10,Haris Rauf,1,1,0,0,100.00,Not_Out
692,Pakistan Vs England,England,1,Jos Buttler,26,17,3,1,152.94,Out
693,Pakistan Vs England,England,2,Alex Hales,1,2,0,0,50.00,Out
694,Pakistan Vs England,England,3,Phil Salt,10,9,2,0,111.11,Out
695,Pakistan Vs England,England,4,Ben Stokes,52,49,5,1,106.12,Not_Out
696,Pakistan Vs England,England,5,Harry Brook,20,23,1,0,86.95,Out
697,Pakistan Vs England,England,6,Moeen Ali,19,13,3,0,146.15,Out
698,Pakistan Vs England,England,7,Liam Livingstone,1,1,0,0,100.00,Not_Out

In [76]:
match_dicts={}
for index, row in df.iterrows():
    key1=row['team1']+' Vs '+row['team2']
    key2=row['team2']+' Vs '+row['team1']

    match_dicts[key1]=row['match_id']
    match_dicts[key2]=row['match_id']
print(match_dicts)

{'Namibia Vs Sri Lanka': 'T20I # 1823', 'Sri Lanka Vs Namibia': 'T20I # 1823', 'Netherlands Vs U.A.E.': 'T20I # 1825', 'U.A.E. Vs Netherlands': 'T20I # 1825', 'Scotland Vs West Indies': 'T20I # 1826', 'West Indies Vs Scotland': 'T20I # 1826', 'Ireland Vs Zimbabwe': 'T20I # 1828', 'Zimbabwe Vs Ireland': 'T20I # 1828', 'Namibia Vs Netherlands': 'T20I # 1830', 'Netherlands Vs Namibia': 'T20I # 1830', 'Sri Lanka Vs U.A.E.': 'T20I # 1832', 'U.A.E. Vs Sri Lanka': 'T20I # 1832', 'Ireland Vs Scotland': 'T20I # 1833', 'Scotland Vs Ireland': 'T20I # 1833', 'West Indies Vs Zimbabwe': 'T20I # 1834', 'Zimbabwe Vs West Indies': 'T20I # 1834', 'Netherlands Vs Sri Lanka': 'T20I # 1835', 'Sri Lanka Vs Netherlands': 'T20I # 1835', 'Namibia Vs U.A.E.': 'T20I # 1836', 'U.A.E. Vs Namibia': 'T20I # 1836', 'Ireland Vs West Indies': 'T20I # 1837', 'West Indies Vs Ireland': 'T20I # 1837', 'Scotland Vs Zimbabwe': 'T20I # 1838', 'Zimbabwe Vs Scotland': 'T20I # 1838', 'Australia Vs New Zealand': 'T20I # 1839', 'New Zealand Vs Australia': 'T20I # 1839', 'Afghanistan Vs England': 'T20I # 1840', 'England Vs Afghanistan': 'T20I # 1840', 'Ireland Vs Sri Lanka': 'T20I # 1841', 'Sri Lanka Vs Ireland': 'T20I # 1841', 'India Vs Pakistan': 'T20I # 1842', 'Pakistan Vs India': 'T20I # 1842', 'Bangladesh Vs Netherlands': 'T20I # 1843', 'Netherlands Vs Bangladesh': 'T20I # 1843', 'South Africa Vs Zimbabwe': 'T20I # 1844', 'Zimbabwe Vs South Africa': 'T20I # 1844', 'Australia Vs Sri Lanka': 'T20I # 1845', 'Sri Lanka Vs Australia': 'T20I # 1845', 'England Vs Ireland': 'T20I # 1846', 'Ireland Vs England': 'T20I # 1846', 'Afghanistan Vs New Zealand': 'T20I # 1846a', 'New Zealand Vs Afghanistan': 'T20I # 1846a', 'Bangladesh Vs South Africa': 'T20I # 1847', 'South Africa Vs Bangladesh': 'T20I # 1847', 'India Vs Netherlands': 'T20I # 1848', 'Netherlands Vs India': 'T20I # 1848', 'Pakistan Vs Zimbabwe': 'T20I # 1849', 'Zimbabwe Vs Pakistan': 'T20I # 1849', 'Afghanistan Vs Ireland': 'T20I # 1849a', 'Ireland Vs Afghanistan': 'T20I # 1849a', 'Australia Vs England': 'T20I # 1849b', 'England Vs Australia': 'T20I # 1849b', 'New Zealand Vs Sri Lanka': 'T20I # 1850', 'Sri Lanka Vs New Zealand': 'T20I # 1850', 'Bangladesh Vs Zimbabwe': 'T20I # 1851', 'Zimbabwe Vs Bangladesh': 'T20I # 1851', 'Netherlands Vs Pakistan': 'T20I # 1852', 'Pakistan Vs Netherlands': 'T20I # 1852', 'India Vs South Africa': 'T20I # 1853', 'South Africa Vs India': 'T20I # 1853', 'Australia Vs Ireland': 'T20I # 1855', 'Ireland Vs Australia': 'T20I # 1855', 'Afghanistan Vs Sri Lanka': 'T20I # 1856', 'Sri Lanka Vs Afghanistan': 'T20I # 1856', 'England Vs New Zealand': 'T20I # 1858', 'New Zealand Vs England': 'T20I # 1858', 'Netherlands Vs Zimbabwe': 'T20I # 1859', 'Zimbabwe Vs Netherlands': 'T20I # 1859', 'Bangladesh Vs India': 'T20I # 1860', 'India Vs Bangladesh': 'T20I # 1860', 'Pakistan Vs South Africa': 'T20I # 1861', 'South Africa Vs Pakistan': 'T20I # 1861', 'Ireland Vs New Zealand': 'T20I # 1862', 'New Zealand Vs Ireland': 'T20I # 1862', 'Australia Vs Afghanistan': 'T20I # 1864', 'Afghanistan Vs Australia': 'T20I # 1864', 'England Vs Sri Lanka': 'T20I # 1867', 'Sri Lanka Vs England': 'T20I # 1867', 'Netherlands Vs South Africa': 'T20I # 1871', 'South Africa Vs Netherlands': 'T20I # 1871', 'Bangladesh Vs Pakistan': 'T20I # 1872', 'Pakistan Vs Bangladesh': 'T20I # 1872', 'India Vs Zimbabwe': 'T20I # 1873', 'Zimbabwe Vs India': 'T20I # 1873', 'New Zealand Vs Pakistan': 'T20I # 1877', 'Pakistan Vs New Zealand': 'T20I # 1877', 'England Vs India': 'T20I # 1878', 'India Vs England': 'T20I # 1878', 'England Vs Pakistan': 'T20I # 1879', 'Pakistan Vs England': 'T20I # 1879'}

In [77]:
result['match_id']=result['match'].map(match_dicts)

In [78]:
result.head(30)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,Out/Not_Out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,Out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,Out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,Out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,Out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus,20,24,0,0,83.33,Out,T20I # 1823
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,Out,T20I # 1823
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,Out,T20I # 1823
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,Not_Out,T20I # 1823
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,Out,T20I # 1823
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,Out,T20I # 1823
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,Out,T20I # 1823
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,Out,T20I # 1823
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,Out,T20I # 1823
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka,29,23,2,1,126.08,Out,T20I # 1823
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,Out,T20I # 1823
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,Out,T20I # 1823
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,Out,T20I # 1823
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,Out,T20I # 1823
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,Not_Out,T20I # 1823
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,Out,T20I # 1825
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,Out,T20I # 1825
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,Out,T20I # 1825
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,Out,T20I # 1825
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,Out,T20I # 1825
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,Out,T20I # 1825
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan,1,2,0,0,50.00,Out,T20I # 1825
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,Out,T20I # 1825
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,Not_Out,T20I # 1825
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,Not_Out,T20I # 1825
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,Out,T20I # 1825

In [79]:
result.to_csv('batting_Summary.csv', index=False)

## 3). BOWLING SUMMARY

In [80]:
with open('t20_wc_bowling_summary.json') as a:
    data2=json.load(a)
    all_records=[]
    for rec in data2:
        all_records.extend(rec['bowlingSummary'])

In [81]:
df_bowling = pd.DataFrame(all_records)
df_bowling.head(30)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0
10,Namibia Vs Sri Lanka,Namibia,Jan Frylinck,4,0,26,2,6.50,10,0,2,1,0
11,U.A.E. Vs Netherlands,Netherlands,Fred Klaassen,4,0,13,2,3.25,18,0,0,3,0
12,U.A.E. Vs Netherlands,Netherlands,Tim Pringle,4,0,13,1,3.25,11,0,0,0,0
13,U.A.E. Vs Netherlands,Netherlands,Logan van Beek,2,0,19,0,9.50,5,0,2,1,0
14,U.A.E. Vs Netherlands,Netherlands,Bas de Leede,3,0,19,3,6.33,9,2,0,2,0
15,U.A.E. Vs Netherlands,Netherlands,Paul van Meekeren,4,0,21,0,5.25,11,1,0,0,0
16,U.A.E. Vs Netherlands,Netherlands,Roelof van der Merwe,3,0,19,1,6.33,7,0,1,0,0
17,U.A.E. Vs Netherlands,U.A.E.,Junaid Siddique,4,0,24,3,6.00,10,2,0,1,0
18,U.A.E. Vs Netherlands,U.A.E.,Basil Hameed,1,0,7,1,7.00,4,0,1,0,0
19,U.A.E. Vs Netherlands,U.A.E.,Aayan Afzal Khan,3,0,15,1,5.00,8,1,0,0,0
20,U.A.E. Vs Netherlands,U.A.E.,Karthik Meiyappan,4,0,22,1,5.50,11,2,0,0,0
21,U.A.E. Vs Netherlands,U.A.E.,Zahoor Khan,4,0,11,1,2.75,14,0,0,0,0
22,U.A.E. Vs Netherlands,U.A.E.,Zawar Farid,2.5,0,24,0,8.47,2,2,0,0,0
23,U.A.E. Vs Netherlands,U.A.E.,Kashif Daud,1,0,5,0,5.00,1,0,0,0,0
24,Scotland Vs West Indies,West Indies,Kyle Mayers,2,0,24,0,12.00,5,5,0,2,0
25,Scotland Vs West Indies,West Indies,Akeal Hosein,4,0,31,0,7.75,8,2,1,0,0
26,Scotland Vs West Indies,West Indies,Alzarri Joseph,4,0,28,2,7.00,9,3,0,2,0
27,Scotland Vs West Indies,West Indies,Obed McCoy,3,0,25,0,8.33,6,4,0,0,0
28,Scotland Vs West Indies,West Indies,Jason Holder,3,0,14,2,4.66,8,1,0,0,0
29,Scotland Vs West Indies,West Indies,Odean Smith,4,0,31,1,7.75,6,3,0,1,0

In [82]:
df_bowling.shape

(500, 13)

In [83]:
df_bowling['match_id'] = df_bowling['match'].map(match_dicts)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823

In [84]:
df_bowling.to_csv('bowling_Summary.csv', index=False)

## PLAYER INFORMATION

In [85]:
with open('t20_wc_player_info.json') as b:
    data3=json.load(b)

In [86]:
df_info=pd.DataFrame(data3)

In [87]:
df_info.head(30)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,Associate Nation
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,Associate Nation
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,Associate Nation
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,Associate Nation
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,Associate Nation
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,Associate Nation
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,Associate Nation
8,Pathum Nissanka,Sri Lanka,Right hand Bat,Does Not Bowl,Top order Batter,Scores Quickly in Powerplay
9,Kusal Mendis†,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka(c),Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,"Death over Specialist, Can Score Handy Runs wi..."
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,"Medium built,Outswing bowler can bowl at any ..."
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,"Mystery Bowler, Bowls in powerplay, middle ove..."
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,Associate Nation
20,Bernard Scholtz,Namibia,Right hand Bat,Slow Left arm Orthodox,Bowler,Bernard Scholtz's brother Nicolaas is currentl...
21,Ben Shikongo,Namibia,Right hand Bat,Right arm Medium fast,Bowler,Associate Nation
22,Charith Asalanka,Sri Lanka,Left hand Bat,Right arm Offbreak,Batting Allrounder,One down batter with good technique against s...
23,David Warner,Australia,Left hand Bat,Legbreak,Opening Batter,David Warner's extraordinary batting feats in ...
24,Aaron Finch(c),Australia,Right hand Bat,Slow Left arm Orthodox,Top order Batter,"A solidly built, aggressive batter from a coun..."
25,Mitchell Marsh,Australia,Right hand Bat,Right arm Medium,Allrounder,Part of one of the most well-known family name...
26,Glenn Maxwell,Australia,Right hand Bat,Right arm Offbreak,Batting Allrounder,"One of the fastest scorers in world cricket, G..."
27,Marcus Stoinis,Australia,Right hand Bat,Right arm Medium,Batting Allrounder,"A powerful, versatile batter and medium-pace b..."
28,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,A tall and accurate fast bowler who is unrelen...
29,Pat Cummins,Australia,Right hand Bat,Right arm Fast,Bowler,Earmarked as a potential star from a young age...

In [88]:
df_info['name'] = df_info['name'].apply(lambda x: x.replace('(c)†',''))
df_info['name'] = df_info['name'].apply(lambda x: x.replace('†',''))
df_info['name'] = df_info['name'].apply(lambda x: x.replace('(c)',''))

In [93]:
df_info.head(50)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,Associate Nation
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,Associate Nation
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,Associate Nation
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,Associate Nation
4,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,Associate Nation
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,Associate Nation
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,Associate Nation
8,Pathum Nissanka,Sri Lanka,Right hand Bat,Does Not Bowl,Top order Batter,Scores Quickly in Powerplay
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka,Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,"Death over Specialist, Can Score Handy Runs wi..."
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,"Medium built,Outswing bowler can bowl at any ..."
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,"Mystery Bowler, Bowls in powerplay, middle ove..."
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,Associate Nation
20,Bernard Scholtz,Namibia,Right hand Bat,Slow Left arm Orthodox,Bowler,Bernard Scholtz's brother Nicolaas is currentl...
21,Ben Shikongo,Namibia,Right hand Bat,Right arm Medium fast,Bowler,Associate Nation
22,Charith Asalanka,Sri Lanka,Left hand Bat,Right arm Offbreak,Batting Allrounder,One down batter with good technique against s...
23,David Warner,Australia,Left hand Bat,Legbreak,Opening Batter,David Warner's extraordinary batting feats in ...
24,Aaron Finch,Australia,Right hand Bat,Slow Left arm Orthodox,Top order Batter,"A solidly built, aggressive batter from a coun..."
25,Mitchell Marsh,Australia,Right hand Bat,Right arm Medium,Allrounder,Part of one of the most well-known family name...
26,Glenn Maxwell,Australia,Right hand Bat,Right arm Offbreak,Batting Allrounder,"One of the fastest scorers in world cricket, G..."
27,Marcus Stoinis,Australia,Right hand Bat,Right arm Medium,Batting Allrounder,"A powerful, versatile batter and medium-pace b..."
28,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,A tall and accurate fast bowler who is unrelen...
29,Pat Cummins,Australia,Right hand Bat,Right arm Fast,Bowler,Earmarked as a potential star from a young age...
30,Mitchell Starc,Australia,Left hand Bat,Left arm Fast,Bowler,"First there was Johnson, then there was Starc...."
31,Ashton Agar,Australia,Left hand Bat,Slow Left arm Orthodox,Bowler,Ashton Agar initially turned almost as many he...
32,Binura Fernando,Sri Lanka,Right hand Bat,Left arm Medium fast,Bowler,Known for his ability to generate awkward boun...
33,Lahiru Kumara,Sri Lanka,Left hand Bat,Right arm Fast,Bowler,"A robust, right-arm fast bowler from Kandy, La..."
34,Dasun Shanaka,Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
35,Regis Chakabva,Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
36,Craig Ervine,Zimbabwe,Left hand Bat,Right arm Offbreak,Middle order Batter,Few people in Zimbabwe cricket circles were su...
37,Wessly Madhevere,Zimbabwe,Right hand Bat,Right arm Offbreak,Allrounder,Associate Nation
38,Sean Williams,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Middle order Batter,"Sean Williams is a bold, dynamic left-hand bat..."
39,Sikandar Raza,Zimbabwe,Right hand Bat,Right arm Offbreak,Batting Allrounder,Sikandar Raza's story isn't that of your every...
40,Milton Shumba,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Top order Batter,Associate Nation
41,Ryan Burl,Zimbabwe,Left hand Bat,Legbreak,Middle order Batter,Ryan Burl liked playing squash when he was at ...
42,Luke Jongwe,Zimbabwe,Right hand Bat,Right arm Fast medium,Bowler,Associate Nation
43,Paul Stirling,Ireland,Right hand Bat,Right arm Offbreak,Batting Allrounder,Paul Stirling has long been recognised as a fo...
44,Andy Balbirnie,Ireland,Right hand Bat,Right arm Offbreak,Batter,Already one of Ireland's star batters at No. 3...
45,Lorcan Tucker,Ireland,Right hand Bat,Does Not Bowl,Wicketkeeper Batter,Good Young age wicketkeeper
46,Harry Tector,Ireland,Right hand Bat,Right arm Offbreak,Middle order Batter,Born into a cricketing family - his brothers J...
47,Curtis Campher,Ireland,Right hand Bat,Right arm Medium fast,Allrounder,"Born in Johannesburg, raised in South Africa a..."
48,George Dockrell,Ireland,Right hand Bat,Slow Left arm Orthodox,Allrounder,George Dockrell was identified as a left-arm s...
49,Gareth Delany,Ireland,Right hand Bat,Legbreak Googly,Batting Allrounder,Good Allrounder with excellent potential

In [94]:
df_info.isnull().sum()

name            0
team            0
battingStyle    0
bowlingStyle    0
playingRole     0
description     0
dtype: int64

In [95]:
df_info.to_csv('Player_information.csv',index = False)